### ISSUE TITLE
Download link for sample?

### ISSUE THREAD

**Issue by ParzivalWolfram** [Gork3m/MrsMajor-3.0#2]
Hi, my name is Parzival, I'm an admin for [the Malware Wiki](malwiki.org) and I was wondering if you could send me a copy of MrsMajor v3? You can contact me using any method listed [here.](https://malwiki.org/index.php?title=User:ParzivalWolfram) Thanks!

**Comment by ParzivalWolfram** [comment]
> https://tiny.cc/3m

You've given me... a password-protected RAR file. This is, potentially, the requested sample, but it's not exactly helpful.

**Comment by ParzivalWolfram** [comment]
Ah, this is just the dropper. I've had this for a while, actually, I need
the actual sample itself. According to the person using the email as
listed, the code has been lost.

**Comment by Etanomic** [comment]
Can I get around it by compiling the code that we already have?

**Comment by ParzivalWolfram** [comment]
> Can I get around it by compiling the code that we already have?

Sadly, no. All you have here is the dropper, _i think?_

**Comment by Etanomic** [comment]
Yes. And the public code that's here.

**Comment by Etanomic** [comment]
I see.

**Comment by ParzivalWolfram** [comment]
One could PROBABLY get around that, but that's more work than I wanna put in at this point. I also heavily despise Windows developer environments, as I shouldn't need many gigs of VS just for a compiler, etc. etc.

**Comment by Etanomic** [comment]
Ok.

**Comment by Etanomic** [comment]
I hate how it has it's own system that checks if you're inside of a VM_(According to Siam)_, AND you need a key that only 4 people have access to.

**Comment by ParzivalWolfram** [comment]
It's actually 4 keys one person each has, and yes, it does do extensive checks to ensure you're in a VM.

**Comment by ParzivalWolfram** [comment]
that actually isn't true, Siam got 2 keys by mistake.

**Comment by pankoza-pl** [comment]
despite what the creator says, the code actually compilable and worked for me

**Comment by Etanomic** [comment]
Very epic.
Leo

**Comment by lorenzohappy19** [comment]
> despite what the creator says, the code actually compilable and worked for me (using SharpDevelop, not tested with VS)

how do i do that?

**Comment by Gork3m** [comment]
> I mean, like I said, I disassembled what I could. I even found a backed up, partial list of key hashes from the original server hardcoded into the dropper... in a format I can't recover the original keys from before the sun explodes.
> 
> (yes, that says "horserapistyandere.webhost.com".)
> 
> ![image](https://user-images.githubusercontent.com/30007617/138207982-c81acadd-d147-4625-bc72-68faedfd49d4.png)

Data in KeysDB.txt are in this format:
$HASH$ENCRYPTED_TEXT$

Dropper looks for matching hash and tries to decrypt the data linked to that hash using the key you provide. Decrypted data is a direct link to google drive cdn to fetch the actual exe. 
Dropper saves the key on the disk for main executable to verify. (main exe again checks it in KeysDB.txt)

Unfortunately google removed my KeysDB.txt (wtf?) therefore droppers don't work anymore. I might re build this soon so people can stop asking me for keys. (I've been getting 30 mails about it daily).

Also building current source won't work because it's missing a lot of stuff in runtime dir. They're originally created by the main dropper exe and are embedded resources that you cant find on this repo. 

- Federal#9999

**Comment by Etanomic** [comment]
> > I mean, like I said, I disassembled what I could. I even found a backed up, partial list of key hashes from the original server hardcoded into the dropper... in a format I can't recover the original keys from before the sun explodes.
> > (yes, that says "horserapistyandere.webhost.com".)
> > ![image](https://user-images.githubusercontent.com/30007617/138207982-c81acadd-d147-4625-bc72-68faedfd49d4.png)
> 
> Data in KeysDB.txt are in this format: $HASH$ENCRYPTED_TEXT$
> 
> Dropper looks for matching hash and tries to decrypt the data linked to that hash using the key you provide. Decrypted data is a direct link to google drive cdn to fetch the actual exe. Dropper saves the key on the disk for main executable to verify. (main exe again checks it in KeysDB.txt)
> 
> Unfortunately google removed my KeysDB.txt access (wtf?) and pretty much banned all main executables hosted on drive, therefore droppers don't work anymore. I might re build this soon so people can stop asking me for keys. (I've been getting 30 mails about it daily).
> 
> Also building current source won't work because it's missing a lot of stuff in runtime dir. They're originally created by the main dropper exe and are embedded resources that you cant find on this repo.
> 
> * Federal#9999

Thanks guys for your comtribution.
